### ISSUE TITLE
get_basename() method comment is incorrect

### ISSUE THREAD

**Issue by salcode** [cedaro/structure#1]
Currently, the comment on the `get_basename()` method in the abstract class `Structure_AbstractPlugin` says

> Retrieve the absolute path for the main plugin file.

but I believe it should be

> Retrieve the relative path from the main plugin directory.

See https://github.com/cedaro/structure/blob/master/classes/AbstractPlugin.php#L61

**Comment by bradyvercher** [comment]
Thanks!
